name: CUPS release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to tag image with"
        required: true
        default: "0.0.1"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Generate env variables
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "DATE=$(date +'%Y-%m-%d')" >> ${GITHUB_ENV}
          echo "VERSION=$(date +'%Y.%m.%d')-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./cups
          file: cups/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ GITHUB_REPOSITORY_OWNER }}:latest
            ghcr.io/${{ GITHUB_REPOSITORY_OWNER }}:${{ env.DATE }}
            ghcr.io/${{ GITHUB_REPOSITORY_OWNER }}:${{ github.RUN_NUMBER }}
            ghcr.io/${{ GITHUB_REPOSITORY_OWNER }}:${{ github.event.inputs.version }}
